apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app
  labels:
    app: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
      - name: sharon-jenkins-yolo
        image: 700935310038.dkr.ecr.us-east-1.amazonaws.com/sharon-jenkins-yolo:0.1
        ports:
        - containerPort: 81